### ISSUE TITLE
Strange error when dict key is a list

### ISSUE THREAD

**Issue by ZhiyuanChen** [ZhiyuanChen/CHANfiG#21]
```python
Traceback (most recent call last):
  File "/home/v-zhichen/chanfig/chanfig/flat_dict.py", line 195, in __getitem__
    return self.get(name, default=Null)
  File "/home/v-zhichen/chanfig/chanfig/flat_dict.py", line 188, in get
    if name in self:
TypeError: unhashable type: 'list'
```

**Comment by ZhiyuanChen** [comment]
This error message is actually expected.
